name: Validate Packages
on:
  push:
    branches:
      - '*'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-audit:
    name: Cargo packages audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - run: rustup toolchain install stable --profile minimal
      - name: Restore dependencies
        id: restore-dependencies
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "package-audit"
          shared-key: "-"
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Cargo audit
        run: |
          cargo install cargo-audit
      - name: Validate code
        run: |
          cargo audit      
